const VALIDATE_USER = 'VALIDATE_USER';
const LOADING = 'LOADING';
const SIGNOUT = 'SIGNOUT';
const GET_PLAYLISTS = 'GET_PLAYLISTS';
const GO_TO_VIDEOS = 'GO_TO_VIDEOS';
const ADD_TO_NOW_PLAYING = 'ADD_TO_NOW_PLAYING';
const ADD_COMMENT = 'ADD_COMMENT';

export {
  VALIDATE_USER,
  LOADING,
  SIGNOUT,
  GET_PLAYLISTS,
  GO_TO_VIDEOS,
  ADD_TO_NOW_PLAYING,
  ADD_COMMENT
};
